# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.SmallIntegerField(blank=True, default=2000),
            preserve_default=False,
        ),
    ]
