# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='slug',
        ),
    ]
